[versions]
plugin-android = "7.0.2"
plugin-ktlint = "10.1.0"
plugin-maven = "0.17.0"

kotlin = "1.5.30"
kodein = "7.7.0"
koin = "3.1.2"
leakCanary = "2.7"
appCompat = "1.3.1"
lifecycle = "2.4.0-alpha03"
compose = "1.1.0-alpha03"
composeActivity = "1.3.1"
composeViewModel = "1.0.0-alpha07"

junit = "5.7.2"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "plugin-ktlint" }
plugin-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-maven" }

leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
kodein = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
koin = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-savedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
compose-rxjava = { module = "androidx.compose.runtime:runtime-rxjava3", version.ref = "compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtimeSaveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel" }

junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

[bundles]
plugins = ["plugin-android", "plugin-ktlint",  "plugin-maven", "plugin-kotlin"]