[versions]
plugin-android = "7.0.0"
plugin-ktlint = "10.1.0"
plugin-maven = "0.17.0"

kotlin = "1.5.21"

appCompat = "1.3.1"
compose = "1.0.1"
composeActivity = "1.3.0"

junit = "5.7.2"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "plugin-ktlint" }
plugin-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-maven" }

appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-runtimeSaveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }

junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

[bundles]
plugins = ["plugin-android", "plugin-ktlint",  "plugin-maven", "plugin-kotlin"]